# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ppg_temp')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ppg_temp')
    _ppg_temp = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ppg_temp', [dirname(__file__)])
        except ImportError:
            import _ppg_temp
            return _ppg_temp
        try:
            _mod = imp.load_module('_ppg_temp', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _ppg_temp = swig_import_helper()
    del swig_import_helper
else:
    import _ppg_temp
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def get_time():
    return _ppg_temp.get_time()
get_time = _ppg_temp.get_time

def pause():
    return _ppg_temp.pause()
pause = _ppg_temp.pause

def configureTX(adcOffset, carrierFreq_MHz, tx_phase, amplitude, nPoints):
    return _ppg_temp.configureTX(adcOffset, carrierFreq_MHz, tx_phase, amplitude, nPoints)
configureTX = _ppg_temp.configureTX

def init_ppg():
    return _ppg_temp.init_ppg()
init_ppg = _ppg_temp.init_ppg

def stop_ppg():
    return _ppg_temp.stop_ppg()
stop_ppg = _ppg_temp.stop_ppg

def ppg_element(str_label, firstarg, secondarg=0):
    return _ppg_temp.ppg_element(str_label, firstarg, secondarg)
ppg_element = _ppg_temp.ppg_element

marker_names = {}
def load(args):
    for a_tuple in args:
        if a_tuple[0] == 'marker':
            a_tuple = list(a_tuple)
            marker_idx = len(marker_names)
            print "for marker, converting name",a_tuple[1],"to index",marker_idx
            marker_names[a_tuple[1]] = marker_idx
            a_tuple[1] = marker_idx
        elif a_tuple[0] == 'jumpto':
            a_tuple = list(a_tuple)
            marker_idx = marker_names[a_tuple[1]]
            print "for jump, converting name",a_tuple[1],"to index",marker_idx
            a_tuple[1] = marker_idx
        ppg_element(*a_tuple)


def runBoard():
    return _ppg_temp.runBoard()
runBoard = _ppg_temp.runBoard
# This file is compatible with both classic and new-style classes.


