import configparser
config = configparser.ConfigParser()
config.read('../exp_params_config.ini')
print(config.items('acq_params'))
amplitude = config.get('acq_params','amplitude')
print("amplitude is set to",amplitude)
p90_time = config.get('acq_params','p90')
print("90 time is set to", p90_time)
config.set('acq_params','p90','4.464')
new_p90 = config.get('acq_params','p90')
print("90 time is now",new_p90)
