name: Flake8 Lint

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Get changed files
        id: get_changed_files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }}...${{ github.sha }} --diff-filter=AM | grep '\.py$' | tr '\n' ' ')
          else
            CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} --diff-filter=AM | grep '\.py$' | tr '\n' ' ')
          fi
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run Flake8 on changed files
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            echo "Running Flake8 on changed files: $CHANGED_FILES"
            flake8 --max-line-length=88 --ignore=E231,E501,E225,E226,E261,E306,E293,W293,E741,W291,E265,E302,E305,E203,W503 $CHANGED_FILES
          else
            echo "No Python files were changed."
          fi
        env:
          CHANGED_FILES: ${{ env.CHANGED_FILES }}
