name: Flake8 Lint

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 on changed files
        run: |
          git fetch --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only --diff-filter=d ${{ github.base_ref }}...${{ github.sha }} | grep '\.py$' | tr '\n' ' ')
          if [ -n "$CHANGED_FILES" ]; then
            echo "Running Flake8 on changed files: $CHANGED_FILES"
            flake8 --max-line-length=88 --ignore=E231,E501,E225,E226,E261,E306,E293,W293,E741,W291,E265,E302,E305,E203,W503 $CHANGED_FILES
          else
            echo "No Python files were changed."
          fi
